version: '3.8'


volumes:
  db-data:

services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=xsolladb
      - POSTGRES_PASSWORD=test
    volumes:
      - "db-data:/var/lib/postgresql/data"
  app:
    build:
      context: services/app
      dockerfile: Dockerfile
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/xsolladb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create
      - JS_URL=http://localhost
    image: 'xsolla-school-webapp'
    ports:
      - 8080:8080
    depends_on:
      - postgres
